### ISSUE TITLE
BOTH: Use `set` to override `image.tag` 

### ISSUE THREAD

**Issue by jamesrcounts** [jamesrcounts/MCW-Containers-and-DevOps#4]
https://github.com/jamesrcounts/MCW-Containers-and-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Containers%20and%20DevOps%20-%20Infrastructure%20edition.md#task-7-configure-continuous-delivery-to-the-kubernetes-cluster

In step 20, we need to override image tag with the build number from the pipeline that triggered the release.   This will enable continuous delivery, otherwise the same version deploys over and over again.

Example:

![2019-04-05_10-14-47](https://user-images.githubusercontent.com/1542583/55644759-ae6d9a80-578b-11e9-8353-d870b1b432f1.png)

**Comment by vraposo** [comment]
Done with commit cb99fa5.

NOTE: instead of using the Build.BuildNumber as suggested, it's using the Build.BuildId because the other value can contain whitespace or other invalid label characters (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables)

**Comment by jamesrcounts** [comment]
Yes, it could, in theory.  But we know from looking at the images in the ACR, that the build number in this lab is just an integer.  Anyway, its fine as long as it works :)
